// JSEdumart Bookstore - Kenyan Market Product Data

export interface Product {
  id: string
  name: string
  slug: string
  category: string
  subcategory: string
  brand: string
  description: string
  price: number
  salePrice: number | null
  discount: number
  inStock: boolean
  stockQuantity: number
  sku: string
  image: string
  rating: number
  reviewCount: number
  tags: string[]
  featured: boolean
  trending: boolean
  newArrival: boolean
}

export interface Category {
  id: string
  name: string
  slug: string
  icon: string
  description: string
  count: number
}

export interface CartItem {
  product: Product
  quantity: number
}

export interface Testimonial {
  name: string
  role: string
  text: string
  rating: number
  avatar: string
}

// Kenyan Market Books & Stationery
export const products: Product[] = [
  // --- TEXTBOOKS ---
  {
    id: "JSE001",
    name: "KLB Secondary Mathematics Form 1",
    slug: "klb-secondary-mathematics-form-1",
    category: "textbooks",
    subcategory: "secondary",
    brand: "Kenya Literature Bureau",
    description: "The approved KLB Mathematics textbook for Form 1 students following the CBC curriculum. Covers algebra, geometry, statistics, and more with clear illustrations and practice exercises.",
    price: 890,
    salePrice: 750,
    discount: 16,
    inStock: true,
    stockQuantity: 45,
    sku: "TB-KLB-M1",
    image: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400&h=500&fit=crop",
    rating: 4.7,
    reviewCount: 34,
    tags: ["mathematics", "form 1", "klb", "secondary", "cbc"],
    featured: true,
    trending: true,
    newArrival: false,
  },
  {
    id: "JSE002",
    name: "KLB English Form 2 Students' Book",
    slug: "klb-english-form-2",
    category: "textbooks",
    subcategory: "secondary",
    brand: "Kenya Literature Bureau",
    description: "Comprehensive English textbook for Form 2 covering grammar, comprehension, composition, and literature skills aligned with the CBC syllabus.",
    price: 850,
    salePrice: 720,
    discount: 15,
    inStock: true,
    stockQuantity: 38,
    sku: "TB-KLB-E2",
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=500&fit=crop",
    rating: 4.5,
    reviewCount: 22,
    tags: ["english", "form 2", "klb", "secondary"],
    featured: true,
    trending: false,
    newArrival: false,
  },
  {
    id: "JSE003",
    name: "Longhorn Chemistry Form 3",
    slug: "longhorn-chemistry-form-3",
    category: "textbooks",
    subcategory: "secondary",
    brand: "Longhorn Publishers",
    description: "Longhorn Chemistry for Form 3 students. Covers organic chemistry, acids & bases, and the periodic table with practical experiments.",
    price: 950,
    salePrice: 820,
    discount: 14,
    inStock: true,
    stockQuantity: 30,
    sku: "TB-LH-C3",
    image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400&h=500&fit=crop",
    rating: 4.6,
    reviewCount: 19,
    tags: ["chemistry", "form 3", "longhorn", "secondary"],
    featured: false,
    trending: true,
    newArrival: false,
  },
  {
    id: "JSE004",
    name: "Oxford Primary Science Grade 5 (CBC)",
    slug: "oxford-primary-science-grade-5",
    category: "textbooks",
    subcategory: "primary",
    brand: "Oxford University Press",
    description: "CBC-approved Science textbook for Grade 5 learners with hands-on activities and colorful illustrations making science fun.",
    price: 750,
    salePrice: 650,
    discount: 13,
    inStock: true,
    stockQuantity: 52,
    sku: "TB-OX-S5",
    image: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=400&h=500&fit=crop",
    rating: 4.8,
    reviewCount: 41,
    tags: ["science", "grade 5", "cbc", "primary", "oxford"],
    featured: true,
    trending: false,
    newArrival: true,
  },
  {
    id: "JSE005",
    name: "Spotlight Kiswahili Grade 4 (CBC)",
    slug: "spotlight-kiswahili-grade-4",
    category: "textbooks",
    subcategory: "primary",
    brand: "Spotlight Publishers",
    description: "Engage Grade 4 learners with this vibrant Kiswahili textbook aligned to the CBC curriculum. Covers sarufi, ufahamu, and insha.",
    price: 680,
    salePrice: 580,
    discount: 15,
    inStock: true,
    stockQuantity: 60,
    sku: "TB-SP-K4",
    image: "https://images.unsplash.com/photo-1553729459-uj8hkra82fc2?w=400&h=500&fit=crop",
    rating: 4.4,
    reviewCount: 28,
    tags: ["kiswahili", "grade 4", "cbc", "primary"],
    featured: false,
    trending: false,
    newArrival: true,
  },
  {
    id: "JSE006",
    name: "KLB Biology Form 4",
    slug: "klb-biology-form-4",
    category: "textbooks",
    subcategory: "secondary",
    brand: "Kenya Literature Bureau",
    description: "Complete Biology Form 4 textbook covering genetics, evolution, ecology, and human biology for KCSE preparation.",
    price: 980,
    salePrice: 850,
    discount: 13,
    inStock: true,
    stockQuantity: 25,
    sku: "TB-KLB-B4",
    image: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=400&h=500&fit=crop",
    rating: 4.7,
    reviewCount: 36,
    tags: ["biology", "form 4", "klb", "kcse"],
    featured: true,
    trending: true,
    newArrival: false,
  },
  // --- EXERCISE BOOKS ---
  {
    id: "JSE007",
    name: "Counter Book A4 3-Quire (288 Pages)",
    slug: "counter-book-a4-3quire",
    category: "exercise-books",
    subcategory: "counter-books",
    brand: "Kasuku",
    description: "High-quality Kasuku A4 counter book with 288 ruled pages. Durable hard cover ideal for accounting, notes, and office use.",
    price: 350,
    salePrice: 280,
    discount: 20,
    inStock: true,
    stockQuantity: 200,
    sku: "EB-KA-CB3",
    image: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=400&h=500&fit=crop",
    rating: 4.6,
    reviewCount: 55,
    tags: ["counter book", "a4", "kasuku", "office"],
    featured: true,
    trending: true,
    newArrival: false,
  },
  {
    id: "JSE008",
    name: "Exercise Book 48 Pages (Square Ruled)",
    slug: "exercise-book-48-square",
    category: "exercise-books",
    subcategory: "school-exercise",
    brand: "Top Pen",
    description: "Pack of 10 square-ruled exercise books, 48 pages each. Perfect for mathematics and graph work for primary and secondary students.",
    price: 450,
    salePrice: 380,
    discount: 16,
    inStock: true,
    stockQuantity: 500,
    sku: "EB-TP-48S",
    image: "https://images.unsplash.com/photo-1517842645767-c639042777db?w=400&h=500&fit=crop",
    rating: 4.3,
    reviewCount: 67,
    tags: ["exercise book", "square ruled", "maths", "students"],
    featured: false,
    trending: false,
    newArrival: false,
  },
  {
    id: "JSE009",
    name: "Manila Paper A2 (Assorted Colors, 20 Pack)",
    slug: "manila-paper-a2-assorted",
    category: "exercise-books",
    subcategory: "manila-papers",
    brand: "Excel",
    description: "Assorted color manila papers for art projects, charts, and classroom decorations. Pack of 20 sheets in vibrant colors.",
    price: 600,
    salePrice: 480,
    discount: 20,
    inStock: true,
    stockQuantity: 150,
    sku: "EB-EX-MA2",
    image: "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400&h=500&fit=crop",
    rating: 4.5,
    reviewCount: 33,
    tags: ["manila paper", "art", "colors", "school"],
    featured: false,
    trending: false,
    newArrival: true,
  },
  // --- WRITING INSTRUMENTS ---
  {
    id: "JSE010",
    name: "BIC Cristal Ballpoint Pens (Box of 50)",
    slug: "bic-cristal-pens-50",
    category: "writing-instruments",
    subcategory: "pens",
    brand: "BIC",
    description: "The classic BIC Cristal ballpoint pen. Smooth writing, reliable quality. Box of 50 blue pens for school or office.",
    price: 1200,
    salePrice: 950,
    discount: 21,
    inStock: true,
    stockQuantity: 80,
    sku: "WI-BIC-C50",
    image: "https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400&h=500&fit=crop",
    rating: 4.8,
    reviewCount: 89,
    tags: ["pens", "bic", "ballpoint", "office", "school"],
    featured: true,
    trending: true,
    newArrival: false,
  },
  {
    id: "JSE011",
    name: "Staedtler Noris HB Pencils (Box of 12)",
    slug: "staedtler-noris-hb-12",
    category: "writing-instruments",
    subcategory: "pencils",
    brand: "Staedtler",
    description: "Premium German-made Staedtler Noris HB pencils. Break-resistant lead perfect for writing, drawing, and exams.",
    price: 480,
    salePrice: 420,
    discount: 13,
    inStock: true,
    stockQuantity: 120,
    sku: "WI-ST-N12",
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=500&fit=crop",
    rating: 4.7,
    reviewCount: 44,
    tags: ["pencils", "staedtler", "hb", "students"],
    featured: false,
    trending: false,
    newArrival: false,
  },
  {
    id: "JSE012",
    name: "Whiteboard Markers (Assorted, Pack of 4)",
    slug: "whiteboard-markers-4",
    category: "writing-instruments",
    subcategory: "markers",
    brand: "Artline",
    description: "Artline whiteboard markers in 4 colors (black, blue, red, green). Quick-drying, easy-erase formula for teachers.",
    price: 650,
    salePrice: 550,
    discount: 15,
    inStock: true,
    stockQuantity: 90,
    sku: "WI-AR-WM4",
    image: "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400&h=500&fit=crop",
    rating: 4.4,
    reviewCount: 21,
    tags: ["markers", "whiteboard", "teachers", "artline"],
    featured: false,
    trending: false,
    newArrival: true,
  },
  // --- ART SUPPLIES ---
  {
    id: "JSE013",
    name: "Faber-Castell Colour Pencils (24 Pack)",
    slug: "faber-castell-24-colour",
    category: "art-supplies",
    subcategory: "colour-pencils",
    brand: "Faber-Castell",
    description: "Vibrant 24-color pencil set from Faber-Castell. Rich pigments, smooth application, ideal for art class and creative projects.",
    price: 850,
    salePrice: 720,
    discount: 15,
    inStock: true,
    stockQuantity: 65,
    sku: "AS-FC-CP24",
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=500&fit=crop",
    rating: 4.9,
    reviewCount: 52,
    tags: ["colour pencils", "art", "faber-castell", "drawing"],
    featured: true,
    trending: true,
    newArrival: false,
  },
  {
    id: "JSE014",
    name: "Watercolor Paint Set (12 Colors + Brush)",
    slug: "watercolor-paint-set-12",
    category: "art-supplies",
    subcategory: "paints",
    brand: "Pelikan",
    description: "Professional-quality watercolor set with 12 vibrant colors and a free brush. Perfect for school art projects and creative exploration.",
    price: 550,
    salePrice: 450,
    discount: 18,
    inStock: true,
    stockQuantity: 40,
    sku: "AS-PK-WC12",
    image: "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=400&h=500&fit=crop",
    rating: 4.6,
    reviewCount: 31,
    tags: ["watercolor", "paint", "art", "pelikan"],
    featured: false,
    trending: false,
    newArrival: true,
  },
  {
    id: "JSE015",
    name: "A3 Sketch Pad (50 Sheets, 120gsm)",
    slug: "a3-sketch-pad-50",
    category: "art-supplies",
    subcategory: "sketch-pads",
    brand: "Canson",
    description: "Premium A3 sketch pad with 50 sheets of 120gsm acid-free paper. Ideal for pencil, charcoal, and pastel artwork.",
    price: 780,
    salePrice: 680,
    discount: 13,
    inStock: true,
    stockQuantity: 35,
    sku: "AS-CN-SP50",
    image: "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400&h=500&fit=crop",
    rating: 4.5,
    reviewCount: 18,
    tags: ["sketch pad", "a3", "art", "drawing", "canson"],
    featured: false,
    trending: false,
    newArrival: false,
  },
  // --- SCHOOL STATIONERIES ---
  {
    id: "JSE016",
    name: "Mathematical Instrument Set (Oxford)",
    slug: "oxford-math-set",
    category: "school-stationeries",
    subcategory: "geometry-sets",
    brand: "Oxford",
    description: "Complete geometry set including compass, protractor, set squares, ruler, and divider in a durable plastic case. KCSE approved.",
    price: 350,
    salePrice: 280,
    discount: 20,
    inStock: true,
    stockQuantity: 180,
    sku: "SS-OX-MS1",
    image: "https://images.unsplash.com/photo-1509228627152-72ae9ae6848d?w=400&h=500&fit=crop",
    rating: 4.6,
    reviewCount: 73,
    tags: ["geometry set", "maths", "oxford", "kcse"],
    featured: true,
    trending: false,
    newArrival: false,
  },
  {
    id: "JSE017",
    name: "School Bag (Heavy Duty, 22L)",
    slug: "school-bag-heavy-duty-22l",
    category: "school-stationeries",
    subcategory: "bags",
    brand: "Safari",
    description: "Durable 22-litre school bag with padded straps, multiple compartments, and water bottle holder. Built to last the whole year.",
    price: 2500,
    salePrice: 1950,
    discount: 22,
    inStock: true,
    stockQuantity: 30,
    sku: "SS-SF-BG22",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=500&fit=crop",
    rating: 4.4,
    reviewCount: 29,
    tags: ["school bag", "backpack", "safari", "durable"],
    featured: true,
    trending: true,
    newArrival: true,
  },
  {
    id: "JSE018",
    name: "Scientific Calculator (Casio fx-82ES Plus)",
    slug: "casio-fx82es-calculator",
    category: "school-stationeries",
    subcategory: "calculators",
    brand: "Casio",
    description: "The most popular scientific calculator for Kenyan students. 252 functions, natural display, KNEC approved for KCSE and KCPE exams.",
    price: 1800,
    salePrice: 1500,
    discount: 17,
    inStock: true,
    stockQuantity: 55,
    sku: "SS-CA-FX82",
    image: "https://images.unsplash.com/photo-1564466809058-bf4114d55352?w=400&h=500&fit=crop",
    rating: 4.9,
    reviewCount: 112,
    tags: ["calculator", "casio", "scientific", "kcse", "exams"],
    featured: true,
    trending: true,
    newArrival: false,
  },
  // --- OFFICE STATIONERIES ---
  {
    id: "JSE019",
    name: "A4 Printing Paper (500 Sheets, 80gsm)",
    slug: "a4-printing-paper-500",
    category: "office-stationeries",
    subcategory: "paper",
    brand: "Typek",
    description: "Premium A4 white printing paper, 80gsm. 500-sheet ream suitable for photocopying, printing, and general office use.",
    price: 750,
    salePrice: 650,
    discount: 13,
    inStock: true,
    stockQuantity: 300,
    sku: "OS-TY-A4500",
    image: "https://images.unsplash.com/photo-1517842645767-c639042777db?w=400&h=500&fit=crop",
    rating: 4.5,
    reviewCount: 48,
    tags: ["a4 paper", "printing", "office", "typek"],
    featured: false,
    trending: false,
    newArrival: false,
  },
  {
    id: "JSE020",
    name: "Stapler + Staples Combo (Standard)",
    slug: "stapler-combo-standard",
    category: "office-stationeries",
    subcategory: "staplers",
    brand: "Kangaro",
    description: "Heavy-duty metal stapler with 1000 free staples. Desktop stapler suitable for up to 20 sheets. Built to last.",
    price: 450,
    salePrice: 380,
    discount: 16,
    inStock: true,
    stockQuantity: 75,
    sku: "OS-KG-ST1",
    image: "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=400&h=500&fit=crop",
    rating: 4.3,
    reviewCount: 21,
    tags: ["stapler", "staples", "office", "kangaro"],
    featured: false,
    trending: false,
    newArrival: false,
  },
  {
    id: "JSE021",
    name: "Lever Arch File A4 (Board)",
    slug: "lever-arch-file-a4",
    category: "office-stationeries",
    subcategory: "files",
    brand: "Zep",
    description: "Standard A4 lever arch file with strong clip mechanism. Available in blue. Ideal for document organization in schools and offices.",
    price: 350,
    salePrice: 290,
    discount: 17,
    inStock: true,
    stockQuantity: 100,
    sku: "OS-ZP-LAF",
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=500&fit=crop",
    rating: 4.2,
    reviewCount: 15,
    tags: ["file", "lever arch", "office", "organization"],
    featured: false,
    trending: false,
    newArrival: false,
  },
  {
    id: "JSE022",
    name: "Revision Past Papers KCSE 2015-2024",
    slug: "kcse-past-papers",
    category: "textbooks",
    subcategory: "revision",
    brand: "KLB",
    description: "Complete KCSE past papers compilation from 2015-2024. All subjects included with marking schemes. Essential for exam preparation.",
    price: 1200,
    salePrice: 950,
    discount: 21,
    inStock: true,
    stockQuantity: 40,
    sku: "TB-KLB-PP",
    image: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400&h=500&fit=crop",
    rating: 4.8,
    reviewCount: 87,
    tags: ["past papers", "kcse", "revision", "exams"],
    featured: true,
    trending: true,
    newArrival: false,
  },
  {
    id: "JSE023",
    name: "Crayola Wax Crayons (64 Pack)",
    slug: "crayola-wax-crayons-64",
    category: "art-supplies",
    subcategory: "crayons",
    brand: "Crayola",
    description: "The ultimate crayon set with 64 vibrant colors including built-in sharpener. Non-toxic and safe for young artists. Perfect for PP1/PP2.",
    price: 1100,
    salePrice: 890,
    discount: 19,
    inStock: true,
    stockQuantity: 48,
    sku: "AS-CR-WC64",
    image: "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400&h=500&fit=crop",
    rating: 4.7,
    reviewCount: 39,
    tags: ["crayons", "crayola", "art", "kids", "coloring"],
    featured: false,
    trending: false,
    newArrival: true,
  },
  {
    id: "JSE024",
    name: "Teacher's Record Book (KIE Approved)",
    slug: "teachers-record-book",
    category: "school-stationeries",
    subcategory: "teacher-supplies",
    brand: "KIE",
    description: "Official teacher's record book approved by Kenya Institute of Education. Covers attendance, marks, and student progress tracking.",
    price: 550,
    salePrice: 450,
    discount: 18,
    inStock: true,
    stockQuantity: 90,
    sku: "SS-KIE-TRB",
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=500&fit=crop",
    rating: 4.5,
    reviewCount: 25,
    tags: ["teacher", "record book", "kie", "school"],
    featured: false,
    trending: false,
    newArrival: false,
  },
]

export const categories: Category[] = [
  {
    id: "textbooks",
    name: "Textbooks",
    slug: "textbooks",
    icon: "fa-book",
    description: "KLB, Longhorn, Oxford - CBC and 8-4-4 curriculum textbooks",
    count: 45,
  },
  {
    id: "exercise-books",
    name: "Exercise Books",
    slug: "exercise-books",
    icon: "fa-book-open",
    description: "Counter books, notebooks, manila papers and more",
    count: 32,
  },
  {
    id: "writing-instruments",
    name: "Writing Instruments",
    slug: "writing-instruments",
    icon: "fa-pen",
    description: "Pens, pencils, markers, highlighters and crayons",
    count: 28,
  },
  {
    id: "art-supplies",
    name: "Art Supplies",
    slug: "art-supplies",
    icon: "fa-palette",
    description: "Paints, brushes, sketch pads and craft materials",
    count: 24,
  },
  {
    id: "school-stationeries",
    name: "School Stationeries",
    slug: "school-stationeries",
    icon: "fa-school",
    description: "Bags, calculators, geometry sets and more",
    count: 36,
  },
  {
    id: "office-stationeries",
    name: "Office Stationeries",
    slug: "office-stationeries",
    icon: "fa-briefcase",
    description: "Paper, files, staplers, folders and office essentials",
    count: 22,
  },
  {
    id: "revision",
    name: "Revision Materials",
    slug: "revision",
    icon: "fa-graduation-cap",
    description: "KCSE and KCPE past papers, revision guides",
    count: 18,
  },
  {
    id: "preschool",
    name: "Pre-School",
    slug: "preschool",
    icon: "fa-child",
    description: "PP1/PP2 learning materials, activity books, crayons",
    count: 15,
  },
]

export const testimonials: Testimonial[] = [
  {
    name: "Mary Wanjiku",
    role: "Parent, Nairobi",
    text: "JSEdumart has been a lifesaver for back-to-school shopping. The prices are unbeatable and delivery to Westlands was fast!",
    rating: 5,
    avatar: "MW",
  },
  {
    name: "James Odhiambo",
    role: "Teacher, Kisumu",
    text: "I order all my teaching supplies from JSEdumart. The quality of the Kasuku counter books and KLB textbooks is excellent.",
    rating: 5,
    avatar: "JO",
  },
  {
    name: "Fatma Hassan",
    role: "Student, Mombasa",
    text: "Got my KCSE revision papers and Casio calculator delivered right to my door. Great prices compared to local shops!",
    rating: 4,
    avatar: "FH",
  },
  {
    name: "Peter Kamau",
    role: "School Administrator, Nakuru",
    text: "We buy in bulk for the whole school. JSEdumart always offers the best bulk discounts and their M-Pesa payment is seamless.",
    rating: 5,
    avatar: "PK",
  },
  {
    name: "Grace Njeri",
    role: "Art Teacher, Thika",
    text: "The Faber-Castell colour pencils and Pelikan watercolors are always original. My students love the quality of art supplies from JSEdumart.",
    rating: 5,
    avatar: "GN",
  },
]

export const flashDeals = products.filter((p) => p.discount >= 18)
export const featuredProducts = products.filter((p) => p.featured)
export const trendingProducts = products.filter((p) => p.trending)
export const newArrivals = products.filter((p) => p.newArrival)

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category)
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id)
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase()
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.tags.some((t) => t.toLowerCase().includes(q)) ||
      p.category.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q)
  )
}

export function formatPrice(amount: number): string {
  return `KES ${amount.toLocaleString()}`
}
