export interface Product {
  id: string
  name: string
  slug: string
  category: string
  brand?: string
  description: string
  price: number
  sale_price?: number
  discount?: number
  in_stock: boolean
  stock_quantity: number
  image_url: string
  rating: number
  review_count: number
  featured: boolean
  trending?: boolean
  new_arrival?: boolean
  created_at: string
  updated_at: string
}

export const products: Product[] = [
  // BOOKS
  {
    id: '1',
    name: 'Mathematical Tables',
    slug: 'mathematical-tables',
    category: 'Books, Stationery & Office Supplies',
    brand: 'Books',
    description: 'Essential reference tables for mathematical calculations and formulas',
    price: 250,
    in_stock: true,
    stock_quantity: 75,
    image_url: 'https://images.unsplash.com/photo-1507842217343-583f20270319?w=500&h=500&fit=crop',
    rating: 4.5,
    review_count: 32,
    featured: true,
    trending: false,
    new_arrival: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Sound and Read',
    slug: 'sound-and-read',
    category: 'Books, Stationery & Office Supplies',
    brand: 'Books',
    description: 'Interactive reading and pronunciation guide for learners',
    price: 250,
    in_stock: true,
    stock_quantity: 60,
    image_url: 'https://images.unsplash.com/photo-1507842217343-583f20270319?w=500&h=500&fit=crop',
    rating: 4.3,
    review_count: 28,
    featured: true,
    trending: false,
    new_arrival: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // STATIONERY
  {
    id: '3',
    name: 'Crayons Veda',
    slug: 'crayons-veda',
    category: 'Books, Stationery & Office Supplies',
    brand: 'Stationery',
    description: 'High-quality colored crayons for creative artwork and learning',
    price: 80,
    in_stock: true,
    stock_quantity: 150,
    image_url: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=500&h=500&fit=crop',
    rating: 4.6,
    review_count: 58,
    featured: false,
    trending: true,
    new_arrival: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Crayons Veda (Large Pack)',
    slug: 'crayons-veda-large-pack',
    category: 'Books, Stationery & Office Supplies',
    brand: 'Stationery',
    description: 'Economy pack with extra crayons for schools and offices',
    price: 100,
    in_stock: true,
    stock_quantity: 120,
    image_url: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=500&h=500&fit=crop',
    rating: 4.4,
    review_count: 42,
    featured: false,
    trending: false,
    new_arrival: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Water Colour',
    slug: 'water-colour',
    category: 'Books, Stationery & Office Supplies',
    brand: 'Stationery',
    description: 'Premium water color paints set for artistic expression',
    price: 80,
    in_stock: true,
    stock_quantity: 90,
    image_url: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=500&h=500&fit=crop',
    rating: 4.7,
    review_count: 65,
    featured: false,
    trending: true,
    new_arrival: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'HB Pencils',
    slug: 'hb-pencils',
    category: 'Books, Stationery & Office Supplies',
    brand: 'Stationery',
    description: 'Standard HB pencils perfect for writing and sketching',
    price: 180,
    in_stock: true,
    stock_quantity: 200,
    image_url: 'https://images.unsplash.com/photo-1578502494516-69c3a8b61fa1?w=500&h=500&fit=crop',
    rating: 4.2,
    review_count: 95,
    featured: false,
    trending: false,
    new_arrival: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Pens',
    slug: 'pens',
    category: 'Books, Stationery & Office Supplies',
    brand: 'Stationery',
    description: 'Smooth-writing ballpoint pens for everyday use',
    price: 10,
    in_stock: true,
    stock_quantity: 500,
    image_url: 'https://images.unsplash.com/photo-1578502494516-69c3a8b61fa1?w=500&h=500&fit=crop',
    rating: 4.0,
    review_count: 112,
    featured: false,
    trending: false,
    new_arrival: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Erasers',
    slug: 'erasers',
    category: 'Books, Stationery & Office Supplies',
    brand: 'Stationery',
    description: 'Effective erasers for pencil and chalk marks',
    price: 10,
    in_stock: true,
    stock_quantity: 400,
    image_url: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=500&h=500&fit=crop',
    rating: 3.9,
    review_count: 48,
    featured: false,
    trending: false,
    new_arrival: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '9',
    name: 'Sharpeners',
    slug: 'sharpeners',
    category: 'Books, Stationery & Office Supplies',
    brand: 'Stationery',
    description: 'Durable pencil sharpeners for maintaining sharp writing tips',
    price: 10,
    in_stock: true,
    stock_quantity: 350,
    image_url: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=500&h=500&fit=crop',
    rating: 4.1,
    review_count: 56,
    featured: false,
    trending: false,
    new_arrival: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '10',
    name: 'Helix Oxford Mathematical Set',
    slug: 'helix-oxford-mathematical-set',
    category: 'Books, Stationery & Office Supplies',
    brand: 'Stationery',
    description: 'Complete mathematical instrument set for geometry and calculations',
    price: 350,
    in_stock: true,
    stock_quantity: 85,
    image_url: 'https://images.unsplash.com/photo-1577720643272-265f434a6e7f?w=500&h=500&fit=crop',
    rating: 4.8,
    review_count: 73,
    featured: true,
    trending: true,
    new_arrival: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // OFFICE SUPPLIES
  {
    id: '11',
    name: 'Ream Paper',
    slug: 'ream-paper',
    category: 'Books, Stationery & Office Supplies',
    brand: 'Office Supplies',
    description: 'Standard A4 ream paper for printing and copying',
    price: 750,
    in_stock: true,
    stock_quantity: 110,
    image_url: 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=500&h=500&fit=crop',
    rating: 4.4,
    review_count: 78,
    featured: true,
    trending: false,
    new_arrival: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '12',
    name: 'Manila Paper',
    slug: 'manila-paper',
    category: 'Books, Stationery & Office Supplies',
    brand: 'Office Supplies',
    description: 'Durable manila paper for filing and archival purposes',
    price: 20,
    in_stock: true,
    stock_quantity: 300,
    image_url: 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=500&h=500&fit=crop',
    rating: 4.0,
    review_count: 34,
    featured: false,
    trending: false,
    new_arrival: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '13',
    name: 'Luminous Paper',
    slug: 'luminous-paper',
    category: 'Books, Stationery & Office Supplies',
    brand: 'Office Supplies',
    description: 'Special luminous paper for visibility and presentation',
    price: 50,
    in_stock: true,
    stock_quantity: 200,
    image_url: 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=500&h=500&fit=crop',
    rating: 4.3,
    review_count: 45,
    featured: false,
    trending: true,
    new_arrival: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '14',
    name: 'Office Glue',
    slug: 'office-glue',
    category: 'Books, Stationery & Office Supplies',
    brand: 'Office Supplies',
    description: 'Strong adhesive glue for office and craft projects',
    price: 50,
    in_stock: true,
    stock_quantity: 180,
    image_url: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500&h=500&fit=crop',
    rating: 4.2,
    review_count: 52,
    featured: false,
    trending: false,
    new_arrival: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '15',
    name: 'Spring File',
    slug: 'spring-file',
    category: 'Books, Stationery & Office Supplies',
    brand: 'Office Supplies',
    description: 'Reliable spring files for document organization',
    price: 50,
    in_stock: true,
    stock_quantity: 160,
    image_url: 'https://images.unsplash.com/photo-1577720643272-265f434a6e7f?w=500&h=500&fit=crop',
    rating: 4.1,
    review_count: 38,
    featured: false,
    trending: false,
    new_arrival: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '16',
    name: 'Cellotape',
    slug: 'cellotape',
    category: 'Books, Stationery & Office Supplies',
    brand: 'Office Supplies',
    description: 'Clear adhesive tape for sealing and securing documents',
    price: 50,
    in_stock: true,
    stock_quantity: 220,
    image_url: 'https://images.unsplash.com/photo-1577720643272-265f434a6e7f?w=500&h=500&fit=crop',
    rating: 4.5,
    review_count: 61,
    featured: false,
    trending: false,
    new_arrival: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
