export interface Product {
  id: string
  name: string
  slug: string
  category: string
  brand?: string
  description: string
  price: number
  sale_price?: number
  discount?: number
  in_stock: boolean
  stock_quantity: number
  image_url: string
  rating: number
  review_count: number
  featured: boolean
  trending?: boolean
  new_arrival?: boolean
  created_at: string
  updated_at: string
}

export const products: Product[] = [
  {
    id: '1',
    name: 'The Great Gatsby',
    slug: 'the-great-gatsby',
    category: 'Fiction',
    brand: 'Penguin Classics',
    description: 'A masterpiece of American literature exploring themes of love, wealth, and the American Dream',
    price: 12.99,
    sale_price: 9.99,
    discount: 23,
    in_stock: true,
    stock_quantity: 50,
    image_url: 'https://images.unsplash.com/photo-1543002588-d83fb7f34b47?w=400&h=600&fit=crop',
    rating: 4.5,
    review_count: 128,
    featured: true,
    trending: false,
    new_arrival: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'To Kill a Mockingbird',
    slug: 'to-kill-a-mockingbird',
    category: 'Fiction',
    brand: 'Harper & Row',
    description: 'A gripping tale of racial injustice and childhood innocence by Harper Lee',
    price: 14.99,
    sale_price: 11.99,
    discount: 20,
    in_stock: true,
    stock_quantity: 45,
    image_url: 'https://images.unsplash.com/photo-1507842217343-583f7270bfba?w=400&h=600&fit=crop',
    rating: 4.7,
    review_count: 256,
    featured: true,
    trending: true,
    new_arrival: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: '1984',
    slug: '1984',
    category: 'Science Fiction',
    brand: 'Secker & Warburg',
    description: 'A dystopian masterpiece depicting a totalitarian society and surveillance state',
    price: 13.99,
    sale_price: 10.99,
    discount: 21,
    in_stock: true,
    stock_quantity: 30,
    image_url: 'https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?w=400&h=600&fit=crop',
    rating: 4.6,
    review_count: 342,
    featured: true,
    trending: true,
    new_arrival: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Pride and Prejudice',
    slug: 'pride-and-prejudice',
    category: 'Romance',
    brand: 'John Murray',
    description: 'A romantic novel of manners with timeless themes of love and social class by Jane Austen',
    price: 11.99,
    sale_price: 9.49,
    discount: 21,
    in_stock: true,
    stock_quantity: 60,
    image_url: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=400&h=600&fit=crop',
    rating: 4.8,
    review_count: 189,
    featured: true,
    trending: false,
    new_arrival: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'The Catcher in the Rye',
    slug: 'the-catcher-in-the-rye',
    category: 'Fiction',
    brand: 'Little, Brown',
    description: 'A controversial novel about adolescent alienation and rebellion by J.D. Salinger',
    price: 13.99,
    in_stock: true,
    stock_quantity: 25,
    image_url: 'https://images.unsplash.com/photo-1519995889033-1cd74a8bb6a9?w=400&h=600&fit=crop',
    rating: 4.2,
    review_count: 156,
    featured: true,
    trending: false,
    new_arrival: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'The Hobbit',
    slug: 'the-hobbit',
    category: 'Fantasy',
    brand: 'Allen & Unwin',
    description: 'An epic fantasy adventure following Bilbo Baggins through a perilous journey by J.R.R. Tolkien',
    price: 15.99,
    sale_price: 12.99,
    discount: 19,
    in_stock: true,
    stock_quantity: 40,
    image_url: 'https://images.unsplash.com/photo-1507842217343-583f7270bfba?w=400&h=600&fit=crop',
    rating: 4.7,
    review_count: 212,
    featured: true,
    trending: true,
    new_arrival: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Dune',
    slug: 'dune',
    category: 'Science Fiction',
    brand: 'Chilton Books',
    description: 'An epic science fiction saga of politics, religion, and ecology on a desert planet',
    price: 18.99,
    sale_price: 14.99,
    discount: 21,
    in_stock: true,
    stock_quantity: 35,
    image_url: 'https://images.unsplash.com/photo-1543002588-d83fb7f34b47?w=400&h=600&fit=crop',
    rating: 4.6,
    review_count: 298,
    featured: true,
    trending: true,
    new_arrival: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'The Lord of the Rings',
    slug: 'the-lord-of-the-rings',
    category: 'Fantasy',
    brand: 'Allen & Unwin',
    description: 'An epic fantasy trilogy following the quest to destroy the One Ring by J.R.R. Tolkien',
    price: 25.99,
    sale_price: 19.99,
    discount: 23,
    in_stock: true,
    stock_quantity: 28,
    image_url: 'https://images.unsplash.com/photo-1507842217343-583f7270bfba?w=400&h=600&fit=crop',
    rating: 4.9,
    review_count: 521,
    featured: true,
    trending: true,
    new_arrival: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '9',
    name: 'The Midnight Library',
    slug: 'the-midnight-library',
    category: 'Fiction',
    brand: 'Piatkus',
    description: 'A magical tale of infinite possibilities and life choices by Matt Haig',
    price: 16.99,
    sale_price: 13.49,
    discount: 20,
    in_stock: true,
    stock_quantity: 55,
    image_url: 'https://images.unsplash.com/photo-1543002588-d83fb7f34b47?w=400&h=600&fit=crop',
    rating: 4.4,
    review_count: 287,
    featured: true,
    trending: false,
    new_arrival: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '10',
    name: 'Educated',
    slug: 'educated',
    category: 'Non-Fiction',
    brand: 'Scribner',
    description: 'A powerful memoir about overcoming obstacles and the power of education by Tara Westover',
    price: 19.99,
    sale_price: 15.99,
    discount: 20,
    in_stock: true,
    stock_quantity: 42,
    image_url: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=400&h=600&fit=crop',
    rating: 4.5,
    review_count: 403,
    featured: true,
    trending: false,
    new_arrival: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '11',
    name: 'Atomic Habits',
    slug: 'atomic-habits',
    category: 'Self-Help',
    brand: 'Avery',
    description: 'A practical guide to building good habits and breaking bad ones by James Clear',
    price: 17.99,
    sale_price: 13.99,
    discount: 22,
    in_stock: true,
    stock_quantity: 75,
    image_url: 'https://images.unsplash.com/photo-1507842217343-583f7270bfba?w=400&h=600&fit=crop',
    rating: 4.7,
    review_count: 1247,
    featured: true,
    trending: true,
    new_arrival: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '12',
    name: 'The Silent Patient',
    slug: 'the-silent-patient',
    category: 'Mystery',
    brand: 'Celadon Books',
    description: 'A psychological thriller with a shocking twist about a woman who refuses to speak',
    price: 14.99,
    sale_price: 11.49,
    discount: 23,
    in_stock: true,
    stock_quantity: 38,
    image_url: 'https://images.unsplash.com/photo-1543002588-d83fb7f34b47?w=400&h=600&fit=crop',
    rating: 4.3,
    review_count: 567,
    featured: true,
    trending: true,
    new_arrival: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '13',
    name: 'Sapiens',
    slug: 'sapiens',
    category: 'Non-Fiction',
    brand: 'Harvill Secker',
    description: 'A sweeping history of humankind from the Stone Age to modern times by Yuval Noah Harari',
    price: 21.99,
    sale_price: 17.49,
    discount: 20,
    in_stock: true,
    stock_quantity: 33,
    image_url: 'https://images.unsplash.com/photo-1507842217343-583f7270bfba?w=400&h=600&fit=crop',
    rating: 4.6,
    review_count: 892,
    featured: true,
    trending: false,
    new_arrival: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '14',
    name: 'The Book Thief',
    slug: 'the-book-thief',
    category: 'Fiction',
    brand: 'Picador',
    description: 'A haunting story set in Nazi Germany told from Death\'s perspective by Markus Zusak',
    price: 15.99,
    sale_price: 12.49,
    discount: 22,
    in_stock: true,
    stock_quantity: 47,
    image_url: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=400&h=600&fit=crop',
    rating: 4.5,
    review_count: 678,
    featured: true,
    trending: false,
    new_arrival: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '15',
    name: 'The Alchemist',
    slug: 'the-alchemist',
    category: 'Fiction',
    brand: 'HarperCollins',
    description: 'An inspiring philosophical tale about following your dreams and personal legend by Paulo Coelho',
    price: 12.99,
    sale_price: 10.49,
    discount: 19,
    in_stock: true,
    stock_quantity: 62,
    image_url: 'https://images.unsplash.com/photo-1543002588-d83fb7f34b47?w=400&h=600&fit=crop',
    rating: 4.2,
    review_count: 523,
    featured: true,
    trending: false,
    new_arrival: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '16',
    name: 'Circe',
    slug: 'circe',
    category: 'Fantasy',
    brand: 'Bloomsbury',
    description: 'A reimagining of Greek mythology told from the perspective of the goddess Circe by Madeline Miller',
    price: 16.99,
    sale_price: 13.49,
    discount: 20,
    in_stock: true,
    stock_quantity: 39,
    image_url: 'https://images.unsplash.com/photo-1507842217343-583f7270bfba?w=400&h=600&fit=crop',
    rating: 4.6,
    review_count: 413,
    featured: true,
    trending: true,
    new_arrival: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
